on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  process_fabric:
    if: |
      github.actor != 'github-actions[bot]' &&
      github.event.head_commit.author.name != 'github-actions[bot]' &&
      !startsWith(github.event.head_commit.message, 'Merge') &&
      !startsWith(github.event.head_commit.message, '[ignore-fabric]')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
          printf "INSTRUCTION:\n/fabric improve writing: \n\nINPUT:\n" > fabric_input.md
          cat README.md >> fabric_input.md

      - name: Execute Fabric Patterns
        uses: docker://ghcr.io/xvnpw/fabric-agent-action:v1
        with:
          input_file: "fabric_input.md"
          output_file: "README.md"
          fabric_provider: anthropic
          fabric_model: claude-3-5-sonnet-20240620
          fabric_patterns_included: "clean_text,improve_writing,create_summary"
          debug: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          LANGCHAIN_TRACING_V2: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: create-pull-request/readme
          title: (AI Generated) Improve writing for README.md
          body: Automated pull request based on your changes to README.md. Please review it carefully.
          labels: 'fabric'
          add-paths: |
            README.md
