name: Process Documentation Files

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  process_fabric:
    if: github.actor != 'github-actions[bot]' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last two commits to ensure HEAD~1 is available

      - name: Get changed files
        id: changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- docs/)
          echo "$CHANGED_FILES"
          if [ -z "$CHANGED_FILES" ]; then
            echo "No documentation files changed. Skipping workflow."
            exit 0
          fi
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Prepare Fabric input
        id: prepare_input
        run: |
          {
            echo "fabric improve writing for multiply files. Each file is stating with # FILE filepath, e.g. # FILE docs/text.txt. Return only improved files, without any additional comments or special formatting."
            echo
            while IFS= read -r file; do
              if [ -f "$file" ]; then
                echo "# FILE $file"
                echo
                cat "$file"
                echo -e "\n\n"
              fi
            done <<< "$CHANGED_FILES"
          } > fabric_input.md
        env:
          CHANGED_FILES: ${{ steps.changed_files.outputs.changed_files }}

      - name: Execute Fabric patterns
        uses: docker://ghcr.io/xvnpw/fabric-agent-action:v0.0.21
        with:
          input_file: "fabric_input.md"
          output_file: "fabric_output.md"
          agent_type: react
          fabric_patterns_included: "clean_text,improve_writing,create_summary"
          debug: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGCHAIN_TRACING_V2: "true"
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Update changed files
        id: update_files
        run: |
          # Extract file paths
          mapfile -t FILES < <(grep '^# FILE' fabric_input.md | sed 's/^# FILE //')
          
          # Split output file and update original files
          csplit --prefix=updated_file_ --suffix-format='%02d.md' --quiet fabric_output.md '/^# FILE /' '{*}'
          
          rm -f updated_file_00.md
          
          for i in "${!FILES[@]}"; do
            index=$((i + 1))
            updated_file=$(printf "updated_file_%02d.md" "$index")
            if [[ -f "$updated_file" ]]; then
              sed '1,2d' "$updated_file" > "${FILES[$i]}"
            fi
          done

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "docs: improve documentation writing style (AI-generated)"
          branch: docs/improve-writing
          delete-branch: true
          title: "📝 [AI] Improve documentation writing style"
          body: |
            This PR contains AI-generated improvements to the documentation files.
            
            Modified files:
            ```
            ${{ steps.changed_files.outputs.changed_files }}
            ```
            
            Please review the changes carefully before merging.
          labels: |
            fabric
            documentation
            automated-pr
