name: Process Documentation Files

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'  # Trigger on any change in the docs/ directory
  workflow_dispatch:

jobs:
  process_fabric:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last two commits to ensure HEAD~1 is available

      - name: Get Changed Files
        id: changed_files
        run: |
          # Get the list of files that were added or modified in the last commit within the docs/ directory
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- docs/)
          echo $CHANGED_FILES
          printf "CHANGED_FILES=%s\n" "${CHANGED_FILES}" >> $GITHUB_ENV

      - name: Prepare Fabric Input
        run: |
          # Create an empty fabric input file
          printf "fabric improve writing for multiply files. Each file is stating with # FILE filepath, e.g. # FILE docs/text.txt. Return only improved files, without any additional comments or special formatting.\n\n" > fabric_input.md

          # Only include files that were added or changed
          for file in ${CHANGED_FILES}; do
            if [[ -f "$file" ]]; then
              echo "Processing $file..."
              printf "# FILE $file\n\n" >> fabric_input.md
              cat "$file" >> fabric_input.md
              echo -e "\n\n" >> fabric_input.md
            fi
          done
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}

      - name: Execute Fabric Patterns
        uses: docker://ghcr.io/xvnpw/fabric-agent-action:v0.0.21
        with:
          input_file: "fabric_input.md"
          output_file: "fabric_output.md"
          # agent_provider: "openrouter"
          # agent_model: "openai/o1-preview"
          agent_type: react
          fabric_patterns_included: "clean_text,improve_writing,create_summary"
          debug: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGCHAIN_TRACING_V2: "true"
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Update Changed Files
        run: |
          # Read the file names from fabric_input.md and prepare to update them with content from fabric_output.md
          FILES=()
          while IFS= read -r line; do
            if [[ $line == \#\ FILE* ]]; then
              FILES+=("${line:7}")
            fi
          done < fabric_input.md

          # Split fabric_output.md by file markers to get individual contents
          csplit -f updated_file_ -b '%02d.md' fabric_output.md '/^# FILE /' {*}

          # Remove the first empty file generated by csplit
          rm updated_file_00.md

          # Update the original files with improved content
          index=1
          for file in "${FILES[@]}"; do
            updated_file=$(printf "updated_file_%02d.md" $index)
            if [[ -f "$updated_file" ]]; then
              # Remove the file name header (# filename) from updated content
              tail -n +3 "$updated_file" > "$file"
            fi
            index=$((index + 1))
          done
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: create-pull-request/docs
          title: (AI Generated) Improve writing for modified documentation files
          body: Automated pull request based on your changes to the documentation files. Please review it carefully.
          labels: 'fabric'
          add-paths: |
            docs/**
